### ISSUE TITLE
user data bag and timeperiods

### ISSUE THREAD

**Issue by joshskains** [tas50/nagios#271]
Does not seem to be a way to assign timeperiods to user data bags, but you can to nagios_contacts. But there is no way to assign nagios_contacts to notification groups. In 5.2.0, you got around this by adding a user data bag without an email and a nagios_contacts data bag with a time period. But now it appears that no longer works. Advice please.

**Comment by sbotman** [comment]
By using the new providers, you are able to create any type of configuration item. Also timeperiods are possible now. Please see the wiki: https://github.com/tas50/nagios/wiki/time_periods
Will close this ticket for now but please let me know if I'm interpreting the ticket wrong, then we will re-open this ticket.
