### ISSUE TITLE
Recipe pagerduty does not honor admin_contactgroup : true

### ISSUE THREAD

**Issue by jolexa** [tas50/nagios#288]
I'm trying to get pagerduty to be the default contact for all alerts. However there does not appear to be functionality to achieve this. Any idea on how to make it work?

In the README, it states: "Setting admin_contactgroup to "true" will add this pagerduty contact to the admin contact group created by this cookbook." This doesn't work.

**Comment by sbotman** [comment]
@jolexa the structure of the cookbook has changed a lot. Can you please check it this is still relevant and close the ticket if solved.

**Comment by jolexa** [comment]
No longer a user, can't confirm
