### ISSUE TITLE
hostgroups config file fails on test generation

### ISSUE THREAD

**Issue by howdoicomputer** [tas50/nagios#303]
I have a simple wrapper cookbook that pulls in the default recipe and passes in attribute. I was previously using v5.3.5 on the master branch before this mornings pushes and now I'm using v6.0.0 from the Chef supermarket API.

My kitchen tests are failing because the cookbook is adding an incorrect hostgroup.

define host {
  use server
  address 10.0.2.15
  host_name server-ubuntu-1204.vagrantup.com
  hostgroups _default,all,linux,monitoring
}

Where is that _default coming from?

**Comment by sbotman** [comment]
can you test this with the latest version? think that this issue is solved with the new configuration providers, but not 100% sure..

**Comment by sbotman** [comment]
@howdoicomputer could you please retest this with latest version?

**Comment by howdoicomputer** [comment]
Oh, sorry. I left the company that I was working at when I was working with this cookbook. I am unable to test. :(

**Comment by sbotman** [comment]
Ok, i will close the issue.
