### ISSUE TITLE
Bug in services.cfg.erb (services with the hostgroup `all` missing from the resulting config)

### ISSUE THREAD

**Issue by heaven** [tas50/nagios#322]
Also the validation could be changed to:

```ruby
valid = !!service['hostgroup_name'].split(",").
  find { |s| @hostgroups.include?(s) or @search_hostgroups.include?(s) }
```

**Comment by sbotman** [comment]
With the new model these checks should not be needed any more. Checkout pull request #319 and feel free to share your thoughts on it.

**Comment by heaven** [comment]
Hi, for now I only upgraded to 5.3.4 (because of the refactoring in the gem I can't use the most recent version for now). One thing I noticed is that all our services with host group `all` stopped working. So I had to add:
```
<%
   hostgroups = @hostgroups | ['all']
%>
```
And to remove `service['hostgroup_name'] == "all"` check at all.

**Comment by sbotman** [comment]
@heaven oke with you if we close this? Because cannot reproduce the problem with latest version. Cheers Sander

**Comment by heaven** [comment]
@sbotman sure, the problem only exists in versions <= 5.3.4.
