### ISSUE TITLE
Cookbook breaks if node has tag = nil

### ISSUE THREAD

**Issue by apsey** [tas50/nagios#330]
On file recipes/default.rb, line 119:

if all_nodes.key?('tags') && all_nodes['tags'].include?(exclusion_tag)

If all_nodes is a Hash with a key pointing to a nil value (default config on opscode when no tag is set), then the cookbook breaks.

It should check:

if all_nodes.key?('tags') && not all_nodes['tags'].nil? && all_nodes['tags'].include?(exclusion_tag)

Cheers,

**Comment by sbotman** [comment]
Hi @apsey, I believe that this problem is fixed with the new structure of the cookbook. Could you please test again with latest version? Tnx! Sander

**Comment by sbotman** [comment]
@apsey, could you please give some follow-up. Thanks!

**Comment by apsey** [comment]
@sbotman; Sorry for the delay. We are currently not using your cookbook anymore, so this test makes no sense for us.

Cheers,

**Comment by sbotman** [comment]
Oke, I will close the issue that case. Thanks for the feedback!
