### ISSUE TITLE
Does not pick up ipaddress correctly

### ISSUE THREAD

**Issue by rory** [tas50/nagios#331]
I want to use `node['nagios']['monitoring_interface']` to specify that the NRPE should use this interface to communicate with nodes. However when using vagrant to test this, it was not putting in the ip address of the interface.

The clause `&& node['network']["ipaddress_#{node['nagios']['monitoring_interface']}"]` on `ip_to_monitor` always fails for me. And some [results online](http://stackoverflow.com/questions/14518236/vagrant-how-to-get-hostonly-ip-adress-from-within-chef-recipe) imply that this is not how you get the ip address of interface X.

However I'm new to chef & ruby, so I might have made something wrong.

**Comment by sbotman** [comment]
@rory can you test the latest version of the cookbook and set the wanted address on the node object under `['nagios']['address']` and check if that works?
The new model with the import of all the objects should use this attribute to override the address that it finds by searching for it. You could apply any kind magic you want, just set this attribute and nagios will pickup this setting.

**Comment by sbotman** [comment]
@rory, did you manage to test the suggestion here above?

**Comment by amandasaurus** [comment]
Hi @sbotman , not yet. I see you have reorganised the layout of cookbook since I downloaded it. I have already patched the code, and I haven't put the work in to merge them,

I have a git repo with our chef set up, and I copied the current HEAD into it, so I have lost the history. :( I'm new to chef, so there might be better ways to do this.

**Comment by sbotman** [comment]
Oke @rory, let me know how it works out. Cheers Sander

**Comment by sbotman** [comment]
@rory I have noticed that we had some bugs and the last commit of Bob fixes the problem here.
Can you please test with master and see if the ['nagios']['address'] attribute works for you?

**Comment by sbotman** [comment]
@rory This should work with 7.1.0. Can you test and close if solved :)

**Comment by sbotman** [comment]
Closing this for the moment because I think it's fixed. But feel free to reopen or create a new ticket if needed. Or contact us on gitter for any questions. 

Greetings Sander
